[package]
name = "darkdown"
version = "0.1.0"
authors = ["Leko <leko.noor@gmail.com>"]
edition = "2018"

[lib]
path = "rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.5"
deno_core = "0.47.1"
comrak = "0.7.0"
